name: Sync with Upstream

on:
  schedule:
    - cron: "1 11 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Add Upstream Repository
        run: |
          git remote add https://github.com/openid/AppAuth-iOS
          git fetch upstream master

      - name: Create Branch for Sync
        run: |
          git config --local user.email "webmaster@tag24.de"
          git config --local user.name "tag24-bot"
          git checkout -b sync-upstream-main
          git merge upstream/main --allow-unrelated-histories --no-edit || echo "No changes to merge"

      - name: Push Changes
        run: |
          git push origin sync-upstream-main --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Syncing with upstream repository"
          title: "Sync changes from upstream/main"
          body: "This PR contains the latest updates from the upstream repository."
          base: main
          branch: sync-upstream-main
          labels: "auto-sync"
          assignees: "niklas-tag24"
